/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadTokenRouteImport } from './routes/upload/$token'
import { Route as UTokenRouteImport } from './routes/u/$token'
import { Route as RentalTokenRouteImport } from './routes/rental/$token'
import { Route as ExpenseTokenRouteImport } from './routes/expense/$token'
import { Route as UploadTokenIndexRouteImport } from './routes/upload/$token/index'
import { Route as UTokenIndexRouteImport } from './routes/u/$token/index'
import { Route as RentalTokenIndexRouteImport } from './routes/rental/$token/index'
import { Route as RegisterOrgSlugIndexRouteImport } from './routes/register/$orgSlug/index'
import { Route as QuotePayTokenIndexRouteImport } from './routes/quote/$payToken/index'
import { Route as PayPayTokenIndexRouteImport } from './routes/pay/$payToken/index'
import { Route as NdaTokenIndexRouteImport } from './routes/nda/$token/index'
import { Route as FormOrgSlugIndexRouteImport } from './routes/form/$orgSlug/index'
import { Route as ExpenseTokenIndexRouteImport } from './routes/expense/$token/index'
import { Route as DraftTokenIndexRouteImport } from './routes/draft/$token/index'
import { Route as ContractorIntakeTokenIndexRouteImport } from './routes/contractor-intake/$token/index'
import { Route as AgreementsTokenIndexRouteImport } from './routes/agreements/$token/index'
import { Route as RegisterOrgSlugEventSlugIndexRouteImport } from './routes/register/$orgSlug/$eventSlug/index'
import { Route as FormOrgSlugStaffSlugIndexRouteImport } from './routes/form/$orgSlug/$staffSlug/index'
import { Route as UploadTokenECaseIdIndexRouteImport } from './routes/upload/$token/e/$caseId/index'
import { Route as UTokenECaseIdIndexRouteImport } from './routes/u/$token/e/$caseId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalTokenRoute = RentalTokenRouteImport.update({
  id: '/rental/$token',
  path: '/rental/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseTokenRoute = ExpenseTokenRouteImport.update({
  id: '/expense/$token',
  path: '/expense/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenIndexRoute = UploadTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UploadTokenRoute,
} as any)
const UTokenIndexRoute = UTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UTokenRoute,
} as any)
const RentalTokenIndexRoute = RentalTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RentalTokenRoute,
} as any)
const RegisterOrgSlugIndexRoute = RegisterOrgSlugIndexRouteImport.update({
  id: '/register/$orgSlug/',
  path: '/register/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotePayTokenIndexRoute = QuotePayTokenIndexRouteImport.update({
  id: '/quote/$payToken/',
  path: '/quote/$payToken/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayPayTokenIndexRoute = PayPayTokenIndexRouteImport.update({
  id: '/pay/$payToken/',
  path: '/pay/$payToken/',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaTokenIndexRoute = NdaTokenIndexRouteImport.update({
  id: '/nda/$token/',
  path: '/nda/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormOrgSlugIndexRoute = FormOrgSlugIndexRouteImport.update({
  id: '/form/$orgSlug/',
  path: '/form/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseTokenIndexRoute = ExpenseTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpenseTokenRoute,
} as any)
const DraftTokenIndexRoute = DraftTokenIndexRouteImport.update({
  id: '/draft/$token/',
  path: '/draft/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorIntakeTokenIndexRoute =
  ContractorIntakeTokenIndexRouteImport.update({
    id: '/contractor-intake/$token/',
    path: '/contractor-intake/$token/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgreementsTokenIndexRoute = AgreementsTokenIndexRouteImport.update({
  id: '/agreements/$token/',
  path: '/agreements/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrgSlugEventSlugIndexRoute =
  RegisterOrgSlugEventSlugIndexRouteImport.update({
    id: '/register/$orgSlug/$eventSlug/',
    path: '/register/$orgSlug/$eventSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormOrgSlugStaffSlugIndexRoute =
  FormOrgSlugStaffSlugIndexRouteImport.update({
    id: '/form/$orgSlug/$staffSlug/',
    path: '/form/$orgSlug/$staffSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UploadTokenECaseIdIndexRoute = UploadTokenECaseIdIndexRouteImport.update({
  id: '/e/$caseId/',
  path: '/e/$caseId/',
  getParentRoute: () => UploadTokenRoute,
} as any)
const UTokenECaseIdIndexRoute = UTokenECaseIdIndexRouteImport.update({
  id: '/e/$caseId/',
  path: '/e/$caseId/',
  getParentRoute: () => UTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense/$token': typeof ExpenseTokenRouteWithChildren
  '/rental/$token': typeof RentalTokenRouteWithChildren
  '/u/$token': typeof UTokenRouteWithChildren
  '/upload/$token': typeof UploadTokenRouteWithChildren
  '/agreements/$token': typeof AgreementsTokenIndexRoute
  '/contractor-intake/$token': typeof ContractorIntakeTokenIndexRoute
  '/draft/$token': typeof DraftTokenIndexRoute
  '/expense/$token/': typeof ExpenseTokenIndexRoute
  '/form/$orgSlug': typeof FormOrgSlugIndexRoute
  '/nda/$token': typeof NdaTokenIndexRoute
  '/pay/$payToken': typeof PayPayTokenIndexRoute
  '/quote/$payToken': typeof QuotePayTokenIndexRoute
  '/register/$orgSlug': typeof RegisterOrgSlugIndexRoute
  '/rental/$token/': typeof RentalTokenIndexRoute
  '/u/$token/': typeof UTokenIndexRoute
  '/upload/$token/': typeof UploadTokenIndexRoute
  '/form/$orgSlug/$staffSlug': typeof FormOrgSlugStaffSlugIndexRoute
  '/register/$orgSlug/$eventSlug': typeof RegisterOrgSlugEventSlugIndexRoute
  '/u/$token/e/$caseId': typeof UTokenECaseIdIndexRoute
  '/upload/$token/e/$caseId': typeof UploadTokenECaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreements/$token': typeof AgreementsTokenIndexRoute
  '/contractor-intake/$token': typeof ContractorIntakeTokenIndexRoute
  '/draft/$token': typeof DraftTokenIndexRoute
  '/expense/$token': typeof ExpenseTokenIndexRoute
  '/form/$orgSlug': typeof FormOrgSlugIndexRoute
  '/nda/$token': typeof NdaTokenIndexRoute
  '/pay/$payToken': typeof PayPayTokenIndexRoute
  '/quote/$payToken': typeof QuotePayTokenIndexRoute
  '/register/$orgSlug': typeof RegisterOrgSlugIndexRoute
  '/rental/$token': typeof RentalTokenIndexRoute
  '/u/$token': typeof UTokenIndexRoute
  '/upload/$token': typeof UploadTokenIndexRoute
  '/form/$orgSlug/$staffSlug': typeof FormOrgSlugStaffSlugIndexRoute
  '/register/$orgSlug/$eventSlug': typeof RegisterOrgSlugEventSlugIndexRoute
  '/u/$token/e/$caseId': typeof UTokenECaseIdIndexRoute
  '/upload/$token/e/$caseId': typeof UploadTokenECaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense/$token': typeof ExpenseTokenRouteWithChildren
  '/rental/$token': typeof RentalTokenRouteWithChildren
  '/u/$token': typeof UTokenRouteWithChildren
  '/upload/$token': typeof UploadTokenRouteWithChildren
  '/agreements/$token/': typeof AgreementsTokenIndexRoute
  '/contractor-intake/$token/': typeof ContractorIntakeTokenIndexRoute
  '/draft/$token/': typeof DraftTokenIndexRoute
  '/expense/$token/': typeof ExpenseTokenIndexRoute
  '/form/$orgSlug/': typeof FormOrgSlugIndexRoute
  '/nda/$token/': typeof NdaTokenIndexRoute
  '/pay/$payToken/': typeof PayPayTokenIndexRoute
  '/quote/$payToken/': typeof QuotePayTokenIndexRoute
  '/register/$orgSlug/': typeof RegisterOrgSlugIndexRoute
  '/rental/$token/': typeof RentalTokenIndexRoute
  '/u/$token/': typeof UTokenIndexRoute
  '/upload/$token/': typeof UploadTokenIndexRoute
  '/form/$orgSlug/$staffSlug/': typeof FormOrgSlugStaffSlugIndexRoute
  '/register/$orgSlug/$eventSlug/': typeof RegisterOrgSlugEventSlugIndexRoute
  '/u/$token/e/$caseId/': typeof UTokenECaseIdIndexRoute
  '/upload/$token/e/$caseId/': typeof UploadTokenECaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense/$token'
    | '/rental/$token'
    | '/u/$token'
    | '/upload/$token'
    | '/agreements/$token'
    | '/contractor-intake/$token'
    | '/draft/$token'
    | '/expense/$token/'
    | '/form/$orgSlug'
    | '/nda/$token'
    | '/pay/$payToken'
    | '/quote/$payToken'
    | '/register/$orgSlug'
    | '/rental/$token/'
    | '/u/$token/'
    | '/upload/$token/'
    | '/form/$orgSlug/$staffSlug'
    | '/register/$orgSlug/$eventSlug'
    | '/u/$token/e/$caseId'
    | '/upload/$token/e/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreements/$token'
    | '/contractor-intake/$token'
    | '/draft/$token'
    | '/expense/$token'
    | '/form/$orgSlug'
    | '/nda/$token'
    | '/pay/$payToken'
    | '/quote/$payToken'
    | '/register/$orgSlug'
    | '/rental/$token'
    | '/u/$token'
    | '/upload/$token'
    | '/form/$orgSlug/$staffSlug'
    | '/register/$orgSlug/$eventSlug'
    | '/u/$token/e/$caseId'
    | '/upload/$token/e/$caseId'
  id:
    | '__root__'
    | '/'
    | '/expense/$token'
    | '/rental/$token'
    | '/u/$token'
    | '/upload/$token'
    | '/agreements/$token/'
    | '/contractor-intake/$token/'
    | '/draft/$token/'
    | '/expense/$token/'
    | '/form/$orgSlug/'
    | '/nda/$token/'
    | '/pay/$payToken/'
    | '/quote/$payToken/'
    | '/register/$orgSlug/'
    | '/rental/$token/'
    | '/u/$token/'
    | '/upload/$token/'
    | '/form/$orgSlug/$staffSlug/'
    | '/register/$orgSlug/$eventSlug/'
    | '/u/$token/e/$caseId/'
    | '/upload/$token/e/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpenseTokenRoute: typeof ExpenseTokenRouteWithChildren
  RentalTokenRoute: typeof RentalTokenRouteWithChildren
  UTokenRoute: typeof UTokenRouteWithChildren
  UploadTokenRoute: typeof UploadTokenRouteWithChildren
  AgreementsTokenIndexRoute: typeof AgreementsTokenIndexRoute
  ContractorIntakeTokenIndexRoute: typeof ContractorIntakeTokenIndexRoute
  DraftTokenIndexRoute: typeof DraftTokenIndexRoute
  FormOrgSlugIndexRoute: typeof FormOrgSlugIndexRoute
  NdaTokenIndexRoute: typeof NdaTokenIndexRoute
  PayPayTokenIndexRoute: typeof PayPayTokenIndexRoute
  QuotePayTokenIndexRoute: typeof QuotePayTokenIndexRoute
  RegisterOrgSlugIndexRoute: typeof RegisterOrgSlugIndexRoute
  FormOrgSlugStaffSlugIndexRoute: typeof FormOrgSlugStaffSlugIndexRoute
  RegisterOrgSlugEventSlugIndexRoute: typeof RegisterOrgSlugEventSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental/$token': {
      id: '/rental/$token'
      path: '/rental/$token'
      fullPath: '/rental/$token'
      preLoaderRoute: typeof RentalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$token': {
      id: '/expense/$token'
      path: '/expense/$token'
      fullPath: '/expense/$token'
      preLoaderRoute: typeof ExpenseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token/': {
      id: '/upload/$token/'
      path: '/'
      fullPath: '/upload/$token/'
      preLoaderRoute: typeof UploadTokenIndexRouteImport
      parentRoute: typeof UploadTokenRoute
    }
    '/u/$token/': {
      id: '/u/$token/'
      path: '/'
      fullPath: '/u/$token/'
      preLoaderRoute: typeof UTokenIndexRouteImport
      parentRoute: typeof UTokenRoute
    }
    '/rental/$token/': {
      id: '/rental/$token/'
      path: '/'
      fullPath: '/rental/$token/'
      preLoaderRoute: typeof RentalTokenIndexRouteImport
      parentRoute: typeof RentalTokenRoute
    }
    '/register/$orgSlug/': {
      id: '/register/$orgSlug/'
      path: '/register/$orgSlug'
      fullPath: '/register/$orgSlug'
      preLoaderRoute: typeof RegisterOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$payToken/': {
      id: '/quote/$payToken/'
      path: '/quote/$payToken'
      fullPath: '/quote/$payToken'
      preLoaderRoute: typeof QuotePayTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$payToken/': {
      id: '/pay/$payToken/'
      path: '/pay/$payToken'
      fullPath: '/pay/$payToken'
      preLoaderRoute: typeof PayPayTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda/$token/': {
      id: '/nda/$token/'
      path: '/nda/$token'
      fullPath: '/nda/$token'
      preLoaderRoute: typeof NdaTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$orgSlug/': {
      id: '/form/$orgSlug/'
      path: '/form/$orgSlug'
      fullPath: '/form/$orgSlug'
      preLoaderRoute: typeof FormOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$token/': {
      id: '/expense/$token/'
      path: '/'
      fullPath: '/expense/$token/'
      preLoaderRoute: typeof ExpenseTokenIndexRouteImport
      parentRoute: typeof ExpenseTokenRoute
    }
    '/draft/$token/': {
      id: '/draft/$token/'
      path: '/draft/$token'
      fullPath: '/draft/$token'
      preLoaderRoute: typeof DraftTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-intake/$token/': {
      id: '/contractor-intake/$token/'
      path: '/contractor-intake/$token'
      fullPath: '/contractor-intake/$token'
      preLoaderRoute: typeof ContractorIntakeTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/$token/': {
      id: '/agreements/$token/'
      path: '/agreements/$token'
      fullPath: '/agreements/$token'
      preLoaderRoute: typeof AgreementsTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$orgSlug/$eventSlug/': {
      id: '/register/$orgSlug/$eventSlug/'
      path: '/register/$orgSlug/$eventSlug'
      fullPath: '/register/$orgSlug/$eventSlug'
      preLoaderRoute: typeof RegisterOrgSlugEventSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$orgSlug/$staffSlug/': {
      id: '/form/$orgSlug/$staffSlug/'
      path: '/form/$orgSlug/$staffSlug'
      fullPath: '/form/$orgSlug/$staffSlug'
      preLoaderRoute: typeof FormOrgSlugStaffSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token/e/$caseId/': {
      id: '/upload/$token/e/$caseId/'
      path: '/e/$caseId'
      fullPath: '/upload/$token/e/$caseId'
      preLoaderRoute: typeof UploadTokenECaseIdIndexRouteImport
      parentRoute: typeof UploadTokenRoute
    }
    '/u/$token/e/$caseId/': {
      id: '/u/$token/e/$caseId/'
      path: '/e/$caseId'
      fullPath: '/u/$token/e/$caseId'
      preLoaderRoute: typeof UTokenECaseIdIndexRouteImport
      parentRoute: typeof UTokenRoute
    }
  }
}

interface ExpenseTokenRouteChildren {
  ExpenseTokenIndexRoute: typeof ExpenseTokenIndexRoute
}

const ExpenseTokenRouteChildren: ExpenseTokenRouteChildren = {
  ExpenseTokenIndexRoute: ExpenseTokenIndexRoute,
}

const ExpenseTokenRouteWithChildren = ExpenseTokenRoute._addFileChildren(
  ExpenseTokenRouteChildren,
)

interface RentalTokenRouteChildren {
  RentalTokenIndexRoute: typeof RentalTokenIndexRoute
}

const RentalTokenRouteChildren: RentalTokenRouteChildren = {
  RentalTokenIndexRoute: RentalTokenIndexRoute,
}

const RentalTokenRouteWithChildren = RentalTokenRoute._addFileChildren(
  RentalTokenRouteChildren,
)

interface UTokenRouteChildren {
  UTokenIndexRoute: typeof UTokenIndexRoute
  UTokenECaseIdIndexRoute: typeof UTokenECaseIdIndexRoute
}

const UTokenRouteChildren: UTokenRouteChildren = {
  UTokenIndexRoute: UTokenIndexRoute,
  UTokenECaseIdIndexRoute: UTokenECaseIdIndexRoute,
}

const UTokenRouteWithChildren =
  UTokenRoute._addFileChildren(UTokenRouteChildren)

interface UploadTokenRouteChildren {
  UploadTokenIndexRoute: typeof UploadTokenIndexRoute
  UploadTokenECaseIdIndexRoute: typeof UploadTokenECaseIdIndexRoute
}

const UploadTokenRouteChildren: UploadTokenRouteChildren = {
  UploadTokenIndexRoute: UploadTokenIndexRoute,
  UploadTokenECaseIdIndexRoute: UploadTokenECaseIdIndexRoute,
}

const UploadTokenRouteWithChildren = UploadTokenRoute._addFileChildren(
  UploadTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpenseTokenRoute: ExpenseTokenRouteWithChildren,
  RentalTokenRoute: RentalTokenRouteWithChildren,
  UTokenRoute: UTokenRouteWithChildren,
  UploadTokenRoute: UploadTokenRouteWithChildren,
  AgreementsTokenIndexRoute: AgreementsTokenIndexRoute,
  ContractorIntakeTokenIndexRoute: ContractorIntakeTokenIndexRoute,
  DraftTokenIndexRoute: DraftTokenIndexRoute,
  FormOrgSlugIndexRoute: FormOrgSlugIndexRoute,
  NdaTokenIndexRoute: NdaTokenIndexRoute,
  PayPayTokenIndexRoute: PayPayTokenIndexRoute,
  QuotePayTokenIndexRoute: QuotePayTokenIndexRoute,
  RegisterOrgSlugIndexRoute: RegisterOrgSlugIndexRoute,
  FormOrgSlugStaffSlugIndexRoute: FormOrgSlugStaffSlugIndexRoute,
  RegisterOrgSlugEventSlugIndexRoute: RegisterOrgSlugEventSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
