/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UTokenRouteImport } from './routes/u/$token'
import { Route as UTokenIndexRouteImport } from './routes/u/$token/index'
import { Route as UTokenUploadRouteImport } from './routes/u/$token/upload'
import { Route as UTokenStatusRouteImport } from './routes/u/$token/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenIndexRoute = UTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UTokenRoute,
} as any)
const UTokenUploadRoute = UTokenUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => UTokenRoute,
} as any)
const UTokenStatusRoute = UTokenStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => UTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$token': typeof UTokenRouteWithChildren
  '/u/$token/status': typeof UTokenStatusRoute
  '/u/$token/upload': typeof UTokenUploadRoute
  '/u/$token/': typeof UTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u/$token/status': typeof UTokenStatusRoute
  '/u/$token/upload': typeof UTokenUploadRoute
  '/u/$token': typeof UTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/$token': typeof UTokenRouteWithChildren
  '/u/$token/status': typeof UTokenStatusRoute
  '/u/$token/upload': typeof UTokenUploadRoute
  '/u/$token/': typeof UTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u/$token'
    | '/u/$token/status'
    | '/u/$token/upload'
    | '/u/$token/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u/$token/status' | '/u/$token/upload' | '/u/$token'
  id:
    | '__root__'
    | '/'
    | '/u/$token'
    | '/u/$token/status'
    | '/u/$token/upload'
    | '/u/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UTokenRoute: typeof UTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token/': {
      id: '/u/$token/'
      path: '/'
      fullPath: '/u/$token/'
      preLoaderRoute: typeof UTokenIndexRouteImport
      parentRoute: typeof UTokenRoute
    }
    '/u/$token/upload': {
      id: '/u/$token/upload'
      path: '/upload'
      fullPath: '/u/$token/upload'
      preLoaderRoute: typeof UTokenUploadRouteImport
      parentRoute: typeof UTokenRoute
    }
    '/u/$token/status': {
      id: '/u/$token/status'
      path: '/status'
      fullPath: '/u/$token/status'
      preLoaderRoute: typeof UTokenStatusRouteImport
      parentRoute: typeof UTokenRoute
    }
  }
}

interface UTokenRouteChildren {
  UTokenStatusRoute: typeof UTokenStatusRoute
  UTokenUploadRoute: typeof UTokenUploadRoute
  UTokenIndexRoute: typeof UTokenIndexRoute
}

const UTokenRouteChildren: UTokenRouteChildren = {
  UTokenStatusRoute: UTokenStatusRoute,
  UTokenUploadRoute: UTokenUploadRoute,
  UTokenIndexRoute: UTokenIndexRoute,
}

const UTokenRouteWithChildren =
  UTokenRoute._addFileChildren(UTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UTokenRoute: UTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
