/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UTokenRouteImport } from './routes/u/$token'
import { Route as ExpenseTokenRouteImport } from './routes/expense/$token'
import { Route as UTokenIndexRouteImport } from './routes/u/$token/index'
import { Route as ExpenseTokenIndexRouteImport } from './routes/expense/$token/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseTokenRoute = ExpenseTokenRouteImport.update({
  id: '/expense/$token',
  path: '/expense/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenIndexRoute = UTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UTokenRoute,
} as any)
const ExpenseTokenIndexRoute = ExpenseTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpenseTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expense/$token': typeof ExpenseTokenRouteWithChildren
  '/u/$token': typeof UTokenRouteWithChildren
  '/expense/$token/': typeof ExpenseTokenIndexRoute
  '/u/$token/': typeof UTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expense/$token': typeof ExpenseTokenIndexRoute
  '/u/$token': typeof UTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expense/$token': typeof ExpenseTokenRouteWithChildren
  '/u/$token': typeof UTokenRouteWithChildren
  '/expense/$token/': typeof ExpenseTokenIndexRoute
  '/u/$token/': typeof UTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expense/$token'
    | '/u/$token'
    | '/expense/$token/'
    | '/u/$token/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expense/$token' | '/u/$token'
  id:
    | '__root__'
    | '/'
    | '/expense/$token'
    | '/u/$token'
    | '/expense/$token/'
    | '/u/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpenseTokenRoute: typeof ExpenseTokenRouteWithChildren
  UTokenRoute: typeof UTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$token': {
      id: '/expense/$token'
      path: '/expense/$token'
      fullPath: '/expense/$token'
      preLoaderRoute: typeof ExpenseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token/': {
      id: '/u/$token/'
      path: '/'
      fullPath: '/u/$token/'
      preLoaderRoute: typeof UTokenIndexRouteImport
      parentRoute: typeof UTokenRoute
    }
    '/expense/$token/': {
      id: '/expense/$token/'
      path: '/'
      fullPath: '/expense/$token/'
      preLoaderRoute: typeof ExpenseTokenIndexRouteImport
      parentRoute: typeof ExpenseTokenRoute
    }
  }
}

interface ExpenseTokenRouteChildren {
  ExpenseTokenIndexRoute: typeof ExpenseTokenIndexRoute
}

const ExpenseTokenRouteChildren: ExpenseTokenRouteChildren = {
  ExpenseTokenIndexRoute: ExpenseTokenIndexRoute,
}

const ExpenseTokenRouteWithChildren = ExpenseTokenRoute._addFileChildren(
  ExpenseTokenRouteChildren,
)

interface UTokenRouteChildren {
  UTokenIndexRoute: typeof UTokenIndexRoute
}

const UTokenRouteChildren: UTokenRouteChildren = {
  UTokenIndexRoute: UTokenIndexRoute,
}

const UTokenRouteWithChildren =
  UTokenRoute._addFileChildren(UTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpenseTokenRoute: ExpenseTokenRouteWithChildren,
  UTokenRoute: UTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
