/**
 * Document Category Mapping Utility
 * Maps DocType to DocCategory for file naming and grouping
 *
 * NOTE: DocType and DocCategory types are defined here to avoid
 * circular dependency with @ella/db package. These must be kept
 * in sync with prisma schema.
 */

/**
 * Document category enum (mirrors DocCategory from @ella/db)
 */
export type DocCategory =
  | 'IDENTITY'
  | 'INCOME'
  | 'TAX_RETURNS'
  | 'EXPENSE'
  | 'ASSET'
  | 'EDUCATION'
  | 'HEALTHCARE'
  | 'OTHER'

/**
 * Document type enum (mirrors DocType from @ella/db)
 */
export type DocType =
  // Personal / Identity
  | 'SSN_CARD'
  | 'DRIVER_LICENSE'
  | 'PASSPORT'
  | 'BIRTH_CERTIFICATE'
  | 'ITIN_LETTER'
  | 'MARRIAGE_CERTIFICATE'
  | 'DIVORCE_DECREE'
  | 'GREEN_CARD'
  | 'WORK_VISA'
  | 'NATURALIZATION_CERTIFICATE'
  | 'POWER_OF_ATTORNEY'
  // Employment Income
  | 'W2'
  | 'W2G'
  | 'PAY_STUB'
  | 'EMPLOYMENT_CONTRACT'
  | 'STOCK_OPTION_AGREEMENT'
  | 'RSU_STATEMENT'
  | 'ESPP_STATEMENT'
  // 1099 Series
  | 'FORM_1099_INT'
  | 'FORM_1099_DIV'
  | 'FORM_1099_NEC'
  | 'FORM_1099_MISC'
  | 'FORM_1099_K'
  | 'FORM_1099_R'
  | 'FORM_1099_G'
  | 'FORM_1099_SSA'
  | 'FORM_1099_B'
  | 'FORM_1099_S'
  | 'FORM_1099_C'
  | 'FORM_1099_SA'
  | 'FORM_1099_Q'
  | 'FORM_1099_A'
  | 'FORM_1099_CAP'
  | 'FORM_1099_H'
  | 'FORM_1099_LS'
  | 'FORM_1099_LTC'
  | 'FORM_1099_OID'
  | 'FORM_1099_PATR'
  | 'FORM_1099_QA'
  | 'FORM_1099_SB'
  | 'RRB_1099'
  | 'RRB_1099_R'
  // K-1 Forms
  | 'SCHEDULE_K1'
  | 'SCHEDULE_K1_1065'
  | 'SCHEDULE_K1_1120S'
  | 'SCHEDULE_K1_1041'
  // Health Insurance
  | 'FORM_1095_A'
  | 'FORM_1095_B'
  | 'FORM_1095_C'
  | 'FORM_5498_SA'
  // Education
  | 'FORM_1098_T'
  | 'FORM_1098_E'
  // Deductions / Credits
  | 'FORM_1098'
  | 'FORM_8332'
  // Business Documents
  | 'BANK_STATEMENT'
  | 'PROFIT_LOSS_STATEMENT'
  | 'BALANCE_SHEET'
  | 'BUSINESS_LICENSE'
  | 'EIN_LETTER'
  | 'ARTICLES_OF_INCORPORATION'
  | 'OPERATING_AGREEMENT'
  | 'PAYROLL_REPORT'
  | 'DEPRECIATION_SCHEDULE'
  | 'VEHICLE_MILEAGE_LOG'
  | 'PARTNERSHIP_AGREEMENT'
  | 'SHAREHOLDER_AGREEMENT'
  | 'BUSINESS_INVOICE'
  | 'ACCOUNTS_RECEIVABLE'
  | 'ACCOUNTS_PAYABLE'
  | 'INVENTORY_REPORT'
  | 'SALES_TAX_REPORT'
  // Receipts & Supporting Docs
  | 'RECEIPT'
  | 'DAYCARE_RECEIPT'
  | 'CHARITY_RECEIPT'
  | 'MEDICAL_RECEIPT'
  | 'PROPERTY_TAX_STATEMENT'
  | 'ESTIMATED_TAX_PAYMENT'
  | 'RENT_RECEIPT'
  // Prior Year / IRS
  | 'PRIOR_YEAR_RETURN'
  | 'IRS_NOTICE'
  // Crypto
  | 'CRYPTO_STATEMENT'
  | 'CRYPTO_TAX_REPORT'
  | 'CRYPTO_TRANSACTION_HISTORY'
  | 'STAKING_REWARDS'
  // Foreign
  | 'FOREIGN_BANK_STATEMENT'
  | 'FOREIGN_TAX_STATEMENT'
  | 'FBAR_SUPPORT_DOCS'
  | 'FORM_8938'
  // Real Estate
  | 'CLOSING_DISCLOSURE'
  | 'LEASE_AGREEMENT'
  | 'HUD_1'
  | 'PROPERTY_DEED'
  | 'HOME_APPRAISAL'
  | 'PMI_STATEMENT'
  // Credits / Energy
  | 'EV_PURCHASE_AGREEMENT'
  | 'ENERGY_CREDIT_INVOICE'
  // Additional Business Docs
  | 'FORM_W9_ISSUED'
  | 'MORTGAGE_POINTS_STATEMENT'
  // Extension
  | 'EXTENSION_PAYMENT_PROOF'
  // Tax Returns
  | 'FORM_1040'
  | 'FORM_1040_SR'
  | 'FORM_1040_NR'
  | 'FORM_1040_X'
  | 'STATE_TAX_RETURN'
  | 'FOREIGN_TAX_RETURN'
  | 'TAX_RETURN_TRANSCRIPT'
  // Form 1040 Schedules
  | 'SCHEDULE_C'
  | 'SCHEDULE_SE'
  | 'SCHEDULE_1'
  | 'SCHEDULE_D'
  | 'SCHEDULE_E'
  | 'SCHEDULE_2'
  | 'SCHEDULE_3'
  | 'SCHEDULE_A'
  | 'SCHEDULE_B'
  | 'SCHEDULE_EIC'
  | 'SCHEDULE_F'
  | 'SCHEDULE_H'
  | 'SCHEDULE_J'
  | 'SCHEDULE_R'
  | 'SCHEDULE_8812'
  // Critical IRS Forms
  | 'FORM_2210'
  | 'FORM_2441'
  | 'FORM_2555'
  | 'FORM_3903'
  | 'FORM_4562'
  | 'FORM_4684'
  | 'FORM_4797'
  | 'FORM_4868'
  | 'FORM_5329'
  | 'FORM_5695'
  | 'FORM_6251'
  | 'FORM_8283'
  | 'FORM_8379'
  | 'FORM_8582'
  | 'FORM_8606'
  | 'FORM_8829'
  | 'FORM_8863'
  | 'FORM_8880'
  | 'FORM_8889'
  | 'FORM_8936'
  | 'FORM_8949'
  | 'FORM_8959'
  | 'FORM_8960'
  | 'FORM_8962'
  | 'FORM_8995'
  | 'FORM_8995_A'
  // Investment Documents
  | 'BROKERAGE_STATEMENT'
  | 'TRADE_CONFIRMATION'
  | 'COST_BASIS_STATEMENT'
  | 'MUTUAL_FUND_STATEMENT'
  | 'DIVIDEND_REINVESTMENT'
  // Retirement Documents
  | 'PENSION_STATEMENT'
  | 'IRA_STATEMENT'
  | 'STATEMENT_401K'
  | 'ROTH_IRA_STATEMENT'
  | 'RMD_STATEMENT'
  // Healthcare Documents
  | 'MEDICAL_BILL'
  | 'INSURANCE_EOB'
  | 'HSA_STATEMENT'
  | 'FSA_STATEMENT'
  // Insurance Documents
  | 'AUTO_INSURANCE'
  | 'HOME_INSURANCE'
  | 'LIFE_INSURANCE_STATEMENT'
  | 'DISABILITY_INSURANCE'
  // Legal Documents
  | 'COURT_ORDER'
  | 'SETTLEMENT_AGREEMENT'
  | 'ALIMONY_AGREEMENT'
  | 'CHILD_SUPPORT_ORDER'
  | 'BANKRUPTCY_DOCUMENTS'
  // Childcare Documents
  | 'DAYCARE_STATEMENT'
  | 'DEPENDENT_CARE_FSA'
  | 'NANNY_DOCUMENTATION'
  // Gambling Documents
  | 'GAMBLING_LOSS_STATEMENT'
  // Miscellaneous Documents
  | 'BANK_LETTER'
  | 'LOAN_STATEMENT'
  | 'MEMBERSHIP_DUES'
  | 'PROFESSIONAL_LICENSE'
  // Other
  | 'OTHER'
  | 'UNKNOWN'

/**
 * Deterministic mapping from DocType to DocCategory
 * Used for auto-categorization based on classified document type
 */
export const DOC_TYPE_TO_CATEGORY: Record<DocType, DocCategory> = {
  // IDENTITY - Personal identification documents
  SSN_CARD: 'IDENTITY',
  DRIVER_LICENSE: 'IDENTITY',
  PASSPORT: 'IDENTITY',
  BIRTH_CERTIFICATE: 'IDENTITY',
  ITIN_LETTER: 'IDENTITY',
  MARRIAGE_CERTIFICATE: 'IDENTITY',
  DIVORCE_DECREE: 'IDENTITY',
  GREEN_CARD: 'IDENTITY',
  WORK_VISA: 'IDENTITY',
  NATURALIZATION_CERTIFICATE: 'IDENTITY',
  POWER_OF_ATTORNEY: 'IDENTITY',

  // INCOME - Employment and various income forms
  W2: 'INCOME',
  W2G: 'INCOME',
  PAY_STUB: 'INCOME',
  EMPLOYMENT_CONTRACT: 'INCOME',
  STOCK_OPTION_AGREEMENT: 'INCOME',
  RSU_STATEMENT: 'INCOME',
  ESPP_STATEMENT: 'INCOME',
  FORM_1099_INT: 'INCOME',
  FORM_1099_DIV: 'INCOME',
  FORM_1099_NEC: 'INCOME',
  FORM_1099_MISC: 'INCOME',
  FORM_1099_K: 'INCOME',
  FORM_1099_R: 'INCOME',
  FORM_1099_G: 'INCOME',
  FORM_1099_SSA: 'INCOME',
  FORM_1099_B: 'INCOME',
  FORM_1099_S: 'INCOME',
  FORM_1099_C: 'INCOME',
  FORM_1099_A: 'INCOME',
  FORM_1099_CAP: 'INCOME',
  FORM_1099_H: 'INCOME',
  FORM_1099_LS: 'INCOME',
  FORM_1099_LTC: 'INCOME',
  FORM_1099_OID: 'INCOME',
  FORM_1099_PATR: 'INCOME',
  FORM_1099_QA: 'INCOME',
  FORM_1099_SB: 'INCOME',
  RRB_1099: 'INCOME',
  RRB_1099_R: 'INCOME',
  SCHEDULE_K1: 'INCOME',
  SCHEDULE_K1_1065: 'INCOME',
  SCHEDULE_K1_1120S: 'INCOME',
  SCHEDULE_K1_1041: 'INCOME',
  PENSION_STATEMENT: 'INCOME',
  IRA_STATEMENT: 'INCOME',
  STATEMENT_401K: 'INCOME',
  ROTH_IRA_STATEMENT: 'INCOME',
  RMD_STATEMENT: 'INCOME',
  GAMBLING_LOSS_STATEMENT: 'INCOME',

  // EXPENSE - Receipts and deductible expenses
  RECEIPT: 'EXPENSE',
  DAYCARE_RECEIPT: 'EXPENSE',
  CHARITY_RECEIPT: 'EXPENSE',
  MEDICAL_RECEIPT: 'EXPENSE',
  ESTIMATED_TAX_PAYMENT: 'EXPENSE',
  PROPERTY_TAX_STATEMENT: 'EXPENSE',
  RENT_RECEIPT: 'EXPENSE',
  FORM_1098: 'EXPENSE',
  MEDICAL_BILL: 'EXPENSE',
  INSURANCE_EOB: 'EXPENSE',
  ALIMONY_AGREEMENT: 'EXPENSE',
  CHILD_SUPPORT_ORDER: 'EXPENSE',
  DAYCARE_STATEMENT: 'EXPENSE',
  DEPENDENT_CARE_FSA: 'EXPENSE',
  NANNY_DOCUMENTATION: 'EXPENSE',
  MEMBERSHIP_DUES: 'EXPENSE',

  // ASSET - Property and investment documents
  FORM_1099_SA: 'ASSET',
  FORM_1099_Q: 'ASSET',
  CLOSING_DISCLOSURE: 'ASSET',
  LEASE_AGREEMENT: 'ASSET',
  EV_PURCHASE_AGREEMENT: 'ASSET',
  DEPRECIATION_SCHEDULE: 'ASSET',
  VEHICLE_MILEAGE_LOG: 'ASSET',
  FORM_5498_SA: 'ASSET',
  HUD_1: 'ASSET',
  PROPERTY_DEED: 'ASSET',
  HOME_APPRAISAL: 'ASSET',
  PMI_STATEMENT: 'ASSET',
  BROKERAGE_STATEMENT: 'ASSET',
  TRADE_CONFIRMATION: 'ASSET',
  COST_BASIS_STATEMENT: 'ASSET',
  MUTUAL_FUND_STATEMENT: 'ASSET',
  DIVIDEND_REINVESTMENT: 'ASSET',
  CRYPTO_STATEMENT: 'ASSET',
  CRYPTO_TAX_REPORT: 'ASSET',
  CRYPTO_TRANSACTION_HISTORY: 'ASSET',
  STAKING_REWARDS: 'ASSET',
  AUTO_INSURANCE: 'ASSET',
  HOME_INSURANCE: 'ASSET',
  LIFE_INSURANCE_STATEMENT: 'ASSET',
  DISABILITY_INSURANCE: 'ASSET',
  LOAN_STATEMENT: 'ASSET',

  // EDUCATION - Education-related tax forms
  FORM_1098_T: 'EDUCATION',
  FORM_1098_E: 'EDUCATION',

  // HEALTHCARE - Health insurance forms
  FORM_1095_A: 'HEALTHCARE',
  FORM_1095_B: 'HEALTHCARE',
  FORM_1095_C: 'HEALTHCARE',
  HSA_STATEMENT: 'HEALTHCARE',
  FSA_STATEMENT: 'HEALTHCARE',

  // TAX_RETURNS - Filed tax returns, schedules, and IRS forms
  FORM_1040: 'TAX_RETURNS',
  FORM_1040_SR: 'TAX_RETURNS',
  FORM_1040_NR: 'TAX_RETURNS',
  FORM_1040_X: 'TAX_RETURNS',
  STATE_TAX_RETURN: 'TAX_RETURNS',
  FOREIGN_TAX_RETURN: 'TAX_RETURNS',
  TAX_RETURN_TRANSCRIPT: 'TAX_RETURNS',
  SCHEDULE_C: 'TAX_RETURNS',
  SCHEDULE_SE: 'TAX_RETURNS',
  SCHEDULE_1: 'TAX_RETURNS',
  SCHEDULE_D: 'TAX_RETURNS',
  SCHEDULE_E: 'TAX_RETURNS',
  SCHEDULE_2: 'TAX_RETURNS',
  SCHEDULE_3: 'TAX_RETURNS',
  SCHEDULE_A: 'TAX_RETURNS',
  SCHEDULE_B: 'TAX_RETURNS',
  SCHEDULE_EIC: 'TAX_RETURNS',
  SCHEDULE_F: 'TAX_RETURNS',
  SCHEDULE_H: 'TAX_RETURNS',
  SCHEDULE_J: 'TAX_RETURNS',
  SCHEDULE_R: 'TAX_RETURNS',
  SCHEDULE_8812: 'TAX_RETURNS',
  FORM_2210: 'TAX_RETURNS',
  FORM_2441: 'TAX_RETURNS',
  FORM_2555: 'TAX_RETURNS',
  FORM_3903: 'TAX_RETURNS',
  FORM_4562: 'TAX_RETURNS',
  FORM_4684: 'TAX_RETURNS',
  FORM_4797: 'TAX_RETURNS',
  FORM_4868: 'TAX_RETURNS',
  FORM_5329: 'TAX_RETURNS',
  FORM_5695: 'TAX_RETURNS',
  FORM_6251: 'TAX_RETURNS',
  FORM_8283: 'TAX_RETURNS',
  FORM_8379: 'TAX_RETURNS',
  FORM_8582: 'TAX_RETURNS',
  FORM_8606: 'TAX_RETURNS',
  FORM_8829: 'TAX_RETURNS',
  FORM_8863: 'TAX_RETURNS',
  FORM_8880: 'TAX_RETURNS',
  FORM_8889: 'TAX_RETURNS',
  FORM_8936: 'TAX_RETURNS',
  FORM_8949: 'TAX_RETURNS',
  FORM_8959: 'TAX_RETURNS',
  FORM_8960: 'TAX_RETURNS',
  FORM_8962: 'TAX_RETURNS',
  FORM_8995: 'TAX_RETURNS',
  FORM_8995_A: 'TAX_RETURNS',

  // OTHER - Business documents and miscellaneous
  BANK_STATEMENT: 'OTHER',
  PROFIT_LOSS_STATEMENT: 'OTHER',
  BALANCE_SHEET: 'OTHER',
  BUSINESS_LICENSE: 'OTHER',
  EIN_LETTER: 'OTHER',
  ARTICLES_OF_INCORPORATION: 'OTHER',
  OPERATING_AGREEMENT: 'OTHER',
  PAYROLL_REPORT: 'OTHER',
  PARTNERSHIP_AGREEMENT: 'OTHER',
  SHAREHOLDER_AGREEMENT: 'OTHER',
  BUSINESS_INVOICE: 'OTHER',
  ACCOUNTS_RECEIVABLE: 'OTHER',
  ACCOUNTS_PAYABLE: 'OTHER',
  INVENTORY_REPORT: 'OTHER',
  SALES_TAX_REPORT: 'OTHER',
  PRIOR_YEAR_RETURN: 'OTHER',
  IRS_NOTICE: 'OTHER',
  FOREIGN_BANK_STATEMENT: 'OTHER',
  FOREIGN_TAX_STATEMENT: 'OTHER',
  FBAR_SUPPORT_DOCS: 'OTHER',
  FORM_8938: 'OTHER',
  ENERGY_CREDIT_INVOICE: 'OTHER',
  FORM_W9_ISSUED: 'OTHER',
  MORTGAGE_POINTS_STATEMENT: 'OTHER',
  EXTENSION_PAYMENT_PROOF: 'OTHER',
  FORM_8332: 'OTHER',
  COURT_ORDER: 'OTHER',
  SETTLEMENT_AGREEMENT: 'OTHER',
  BANKRUPTCY_DOCUMENTS: 'OTHER',
  BANK_LETTER: 'OTHER',
  PROFESSIONAL_LICENSE: 'OTHER',

  OTHER: 'OTHER',
  UNKNOWN: 'OTHER',
}

/**
 * Get category from document type
 * Returns 'OTHER' for null/unknown types
 */
export function getCategoryFromDocType(docType: DocType | string | null | undefined): DocCategory {
  if (!docType) return 'OTHER'
  return DOC_TYPE_TO_CATEGORY[docType as DocType] ?? 'OTHER'
}

/**
 * Category display labels (Vietnamese)
 */
export const CATEGORY_LABELS: Record<DocCategory, string> = {
  IDENTITY: 'Giấy tờ tùy thân',
  INCOME: 'Thu nhập',
  TAX_RETURNS: 'Khai Thuế',
  EXPENSE: 'Chi phí',
  ASSET: 'Tài sản',
  EDUCATION: 'Giáo dục',
  HEALTHCARE: 'Y tế',
  OTHER: 'Khác',
}

/**
 * Category order for UI display
 */
export const CATEGORY_ORDER: DocCategory[] = [
  'IDENTITY',
  'INCOME',
  'TAX_RETURNS',
  'EXPENSE',
  'ASSET',
  'EDUCATION',
  'HEALTHCARE',
  'OTHER',
]
