/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ActionsIndexRouteImport } from './routes/actions/index'
import { Route as MessagesCaseIdRouteImport } from './routes/messages/$caseId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as TeamProfileStaffIdRouteImport } from './routes/team/profile/$staffId'
import { Route as CasesCaseIdMessagesRouteImport } from './routes/cases/$caseId/messages'
import { Route as CasesCaseIdEntryRouteImport } from './routes/cases/$caseId/entry'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsIndexRoute = ActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesCaseIdRoute = MessagesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => MessagesRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamProfileStaffIdRoute = TeamProfileStaffIdRouteImport.update({
  id: '/profile/$staffId',
  path: '/profile/$staffId',
  getParentRoute: () => TeamRoute,
} as any)
const CasesCaseIdMessagesRoute = CasesCaseIdMessagesRouteImport.update({
  id: '/cases/$caseId/messages',
  path: '/cases/$caseId/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdEntryRoute = CasesCaseIdEntryRouteImport.update({
  id: '/cases/$caseId/entry',
  path: '/cases/$caseId/entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/messages/$caseId': typeof MessagesCaseIdRoute
  '/actions': typeof ActionsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/cases/$caseId/entry': typeof CasesCaseIdEntryRoute
  '/cases/$caseId/messages': typeof CasesCaseIdMessagesRoute
  '/team/profile/$staffId': typeof TeamProfileStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/messages/$caseId': typeof MessagesCaseIdRoute
  '/actions': typeof ActionsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/cases/$caseId/entry': typeof CasesCaseIdEntryRoute
  '/cases/$caseId/messages': typeof CasesCaseIdMessagesRoute
  '/team/profile/$staffId': typeof TeamProfileStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/messages/$caseId': typeof MessagesCaseIdRoute
  '/actions/': typeof ActionsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/cases/$caseId/entry': typeof CasesCaseIdEntryRoute
  '/cases/$caseId/messages': typeof CasesCaseIdMessagesRoute
  '/team/profile/$staffId': typeof TeamProfileStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/messages'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients/new'
    | '/messages/$caseId'
    | '/actions'
    | '/clients'
    | '/messages/'
    | '/cases/$caseId/entry'
    | '/cases/$caseId/messages'
    | '/team/profile/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients/new'
    | '/messages/$caseId'
    | '/actions'
    | '/clients'
    | '/messages'
    | '/cases/$caseId/entry'
    | '/cases/$caseId/messages'
    | '/team/profile/$staffId'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/messages'
    | '/settings'
    | '/team'
    | '/clients/$clientId'
    | '/clients/new'
    | '/messages/$caseId'
    | '/actions/'
    | '/clients/'
    | '/messages/'
    | '/cases/$caseId/entry'
    | '/cases/$caseId/messages'
    | '/team/profile/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRouteWithChildren
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ActionsIndexRoute: typeof ActionsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  CasesCaseIdEntryRoute: typeof CasesCaseIdEntryRoute
  CasesCaseIdMessagesRoute: typeof CasesCaseIdMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/': {
      id: '/actions/'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$caseId': {
      id: '/messages/$caseId'
      path: '/$caseId'
      fullPath: '/messages/$caseId'
      preLoaderRoute: typeof MessagesCaseIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/profile/$staffId': {
      id: '/team/profile/$staffId'
      path: '/profile/$staffId'
      fullPath: '/team/profile/$staffId'
      preLoaderRoute: typeof TeamProfileStaffIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/cases/$caseId/messages': {
      id: '/cases/$caseId/messages'
      path: '/cases/$caseId/messages'
      fullPath: '/cases/$caseId/messages'
      preLoaderRoute: typeof CasesCaseIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/entry': {
      id: '/cases/$caseId/entry'
      path: '/cases/$caseId/entry'
      fullPath: '/cases/$caseId/entry'
      preLoaderRoute: typeof CasesCaseIdEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesCaseIdRoute: typeof MessagesCaseIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesCaseIdRoute: MessagesCaseIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface TeamRouteChildren {
  TeamProfileStaffIdRoute: typeof TeamProfileStaffIdRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamProfileStaffIdRoute: TeamProfileStaffIdRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRouteWithChildren,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  ActionsIndexRoute: ActionsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  CasesCaseIdEntryRoute: CasesCaseIdEntryRoute,
  CasesCaseIdMessagesRoute: CasesCaseIdMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
