-- Fix: Add all missing DocType enum values to production database
-- This migration consolidates values from:
--   - 20260219_add_schedule_doctypes
--   - 20260224_add_expanded_doctypes
-- Uses IF NOT EXISTS for idempotency (safe to run multiple times)

-- ============================================================
-- PART 1: Schedule DocTypes (from 20260219_add_schedule_doctypes)
-- ============================================================
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_C';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_SE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_1';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_D';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_E';

-- ============================================================
-- PART 2: Expanded DocTypes (from 20260224_add_expanded_doctypes)
-- ============================================================

-- Personal / Identity (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'MARRIAGE_CERTIFICATE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DIVORCE_DECREE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'GREEN_CARD';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'WORK_VISA';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'NATURALIZATION_CERTIFICATE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'POWER_OF_ATTORNEY';

-- Employment Income (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PAY_STUB';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'EMPLOYMENT_CONTRACT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'STOCK_OPTION_AGREEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'RSU_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ESPP_STATEMENT';

-- 1099 Series (new variants)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_A';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_CAP';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_H';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_LS';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_LTC';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_OID';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_PATR';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_QA';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1099_SB';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'RRB_1099';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'RRB_1099_R';

-- Business Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PARTNERSHIP_AGREEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SHAREHOLDER_AGREEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BUSINESS_INVOICE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ACCOUNTS_RECEIVABLE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ACCOUNTS_PAYABLE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'INVENTORY_REPORT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SALES_TAX_REPORT';

-- Receipts (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'RENT_RECEIPT';

-- Crypto (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'CRYPTO_TAX_REPORT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'CRYPTO_TRANSACTION_HISTORY';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'STAKING_REWARDS';

-- Real Estate (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'HUD_1';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PROPERTY_DEED';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'HOME_APPRAISAL';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PMI_STATEMENT';

-- Tax Returns (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1040';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1040_SR';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1040_NR';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_1040_X';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'STATE_TAX_RETURN';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FOREIGN_TAX_RETURN';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'TAX_RETURN_TRANSCRIPT';

-- Form 1040 Schedules (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_2';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_3';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_A';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_B';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_EIC';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_F';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_H';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_J';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_R';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SCHEDULE_8812';

-- Critical IRS Forms (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_2210';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_2441';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_2555';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_3903';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_4562';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_4684';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_4797';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_4868';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_5329';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_5695';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_6251';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8283';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8379';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8582';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8606';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8829';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8863';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8880';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8889';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8936';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8949';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8959';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8960';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8962';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8995';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FORM_8995_A';

-- Investment Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BROKERAGE_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'TRADE_CONFIRMATION';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'COST_BASIS_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'MUTUAL_FUND_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DIVIDEND_REINVESTMENT';

-- Retirement Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PENSION_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'IRA_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'STATEMENT_401K';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ROTH_IRA_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'RMD_STATEMENT';

-- Healthcare Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'MEDICAL_BILL';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'INSURANCE_EOB';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'HSA_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'FSA_STATEMENT';

-- Insurance Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'AUTO_INSURANCE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'HOME_INSURANCE';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'LIFE_INSURANCE_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DISABILITY_INSURANCE';

-- Legal Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'COURT_ORDER';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'SETTLEMENT_AGREEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'ALIMONY_AGREEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'CHILD_SUPPORT_ORDER';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BANKRUPTCY_DOCUMENTS';

-- Childcare Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DAYCARE_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'DEPENDENT_CARE_FSA';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'NANNY_DOCUMENTATION';

-- Gambling Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'GAMBLING_LOSS_STATEMENT';

-- Miscellaneous Documents (new)
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'BANK_LETTER';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'LOAN_STATEMENT';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'MEMBERSHIP_DUES';
ALTER TYPE "DocType" ADD VALUE IF NOT EXISTS 'PROFESSIONAL_LICENSE';

-- ============================================================
-- PART 3: Fix stuck PROCESSING documents
-- Move documents stuck at PROCESSING to CLASSIFIED with OTHER type
-- These are documents where AI classification failed and recovery also failed
-- ============================================================
UPDATE "RawImage"
SET
  "status" = 'CLASSIFIED',
  "classifiedType" = 'OTHER',
  "category" = 'OTHER',
  "aiConfidence" = 0,
  "updatedAt" = NOW()
WHERE
  "status" = 'PROCESSING'
  AND "updatedAt" < NOW() - INTERVAL '1 hour';

-- Log the count of fixed documents (this will be visible in migration output)
DO $$
DECLARE
  fixed_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO fixed_count
  FROM "RawImage"
  WHERE "status" = 'CLASSIFIED'
    AND "classifiedType" = 'OTHER'
    AND "aiConfidence" = 0;
  RAISE NOTICE 'Documents moved from PROCESSING to OTHER: %', fixed_count;
END $$;
