import {
  formatMoney,
  OUT_OF_SCOPE_HOURLY_RATE,
  renderList,
} from './engagement-letter-formatting'

export function renderScopeLimitations(): string[] {
  return [
    '<h3>3. Scope Limitations</h3>',
    '<p><strong>3.1 Services Limited to Those Expressly Stated</strong></p>',
    '<p>Only services specifically listed in this Agreement are included. All other services are excluded.</p>',
    '<p><strong>3.2 Out-of-Scope Services</strong></p>',
    '<p>Out-of-scope services include, without limitation:</p>',
    renderList([
      'Cleanup or reconstruction of prior-period books',
      'Amended tax returns',
      'Amended payroll returns',
      'Tax notice responses',
      'Audit representation',
      'Appeals, hearings, or controversy work',
      'Tax planning or projections',
      'Multi-state tax work not expressly included',
      'Payroll for additional employees',
      'Contractor setup or Forms 1099',
      'Historical reconciliations',
      'Entity restructuring',
      'HR, labor law, benefits, or workers compensation matters',
      'Expedited or rush services',
      'Work caused by late, missing, or inaccurate information',
      'Any service not specifically listed in this Agreement',
    ]),
    '<p><strong>3.3 Out-of-Scope Billing</strong></p>',
    '<p>Out-of-scope services will be billed at the Firm\'s discretion on a flat-fee, per-transaction, or hourly basis.</p>',
    `<p>Standard hourly rate: ${formatMoney(OUT_OF_SCOPE_HOURLY_RATE)}/hour.</p>`,
    '<p>The Firm may require a retainer or separate engagement letter before beginning such services.</p>',
  ]
}

export function renderLegalTerms(): string[] {
  return [
    '<h3>5. Non-Refundable Setup Fees</h3>',
    '<p>Setup fees are fully earned upon engagement and are non-refundable, except where prohibited by law.</p>',
    '<h3>6. Term of Engagement</h3>',
    '<p>This Agreement begins on the Effective Date and continues for a three (3) year initial term.</p>',
    '<p>Client may terminate early only upon permanent business closure or sale of the business. Any other early termination constitutes a material breach unless accepted in writing by the Firm. After the initial term, services may continue month-to-month.</p>',
    '<h3>7. Billing and Payment</h3>',
    '<p><strong>7.1 Payment Terms</strong></p>',
    '<p>Setup fees are due upon signing. Monthly fees are billed in advance. Out-of-scope fees are due upon receipt. Failure to pay is a material breach.</p>',
    '<p><strong>7.2 Auto-Debit Authorization</strong></p>',
    '<p>Client authorizes automatic charges for setup fees, monthly fees, tax filing allocations, out-of-scope services, late fees, failed payment fees, and any amounts due under this Agreement. Client must maintain a valid payment method at all times.</p>',
    '<p><strong>7.3 Failed Payment Fee</strong></p>',
    '<p>Returned or rejected payments may incur a $50 fee, to the extent permitted by law.</p>',
    '<h3>8. Suspension of Services</h3>',
    '<p>The Firm may immediately suspend services for nonpayment. The Firm is not liable for penalties, interest, missed deadlines, rejected filings, or damages resulting from suspension due to Client nonpayment.</p>',
    '<h3>9. Client Responsibilities</h3>',
    '<p>Client agrees to provide accurate and timely information, maintain proper records, review and approve filings, notify Firm of all material changes, remain responsible for management and regulatory decisions, and timely pay all fees. The Firm may rely entirely on Client-provided information.</p>',
    '<h3>10. Nature of Services</h3>',
    '<p>The Firm is not engaged to perform an audit, review, compilation, forensic engagement, legal representation, valuation, or any assurance service.</p>',
    '<p>The Firm does not provide legal advice, investment advice, formal tax opinions, audit representation, litigation support, HR services, or employment law services. Payroll services do not include legal or regulatory analysis.</p>',
    '<h3>11. Audit Monitoring Disclaimer</h3>',
    '<p>If monitoring services are included, those services depend on third-party systems and transcript availability. The Firm does not guarantee prevention of audits, detection of every event, uninterrupted monitoring, prevention of penalties or enforcement, or favorable tax authority outcomes. Notifications are informational only.</p>',
    '<h3>12. Third-Party Providers</h3>',
    '<p>The Firm may use third-party platforms and vendors. The Firm is not liable for outages, price changes, or errors caused by third parties except where finally determined to result solely from the Firm\'s gross negligence or willful misconduct.</p>',
    '<h3>13. Disclaimer of Warranties</h3>',
    '<p>All services are provided as available. The Firm does not guarantee specific outcomes.</p>',
    '<h3>14. Limitation of Liability</h3>',
    '<p>The Firm\'s total aggregate liability is limited to fees paid in the six (6) months preceding the event giving rise to the claim. The Firm is not liable for indirect damages, lost profits, tax penalties or interest, government assessments, or business interruption. Claims must be brought within one (1) year.</p>',
    '<h3>15. Indemnification</h3>',
    '<p>Client agrees to indemnify and hold harmless the Firm from claims arising from Client acts or omissions, inaccurate information, payroll or tax data errors, regulatory violations, or third-party claims based on Client conduct. This provision survives termination.</p>',
    '<h3>16. Early Termination; Acceleration</h3>',
    '<p>If Client improperly terminates early, the Firm may accelerate all unpaid invoices, earned but unbilled fees, setup fees, third-party charges, work-in-process, collection costs, and attorneys fees to the extent permitted by law.</p>',
    '<h3>17. Dispute Resolution</h3>',
    '<p>Disputes shall first be submitted to good-faith mediation. If unresolved, disputes shall be resolved by binding arbitration in the county and state where the Firm maintains its principal office, where permitted by law. Both parties waive jury trial rights. Prevailing party may recover reasonable attorneys fees where permitted by law.</p>',
    '<h3>18. Personal Guaranty</h3>',
    '<p>The undersigned individual personally guarantees all Client obligations under this Agreement. This guaranty is continuing and unconditional.</p>',
    '<h3>19. Records and Electronic Communication</h3>',
    '<p>Client is responsible for retaining original records. Client consents to electronic communication and acknowledges associated risks.</p>',
    '<h3>20. Force Majeure</h3>',
    '<p>The Firm is not liable for delays caused by events beyond its reasonable control.</p>',
    '<h3>21. Governing Law</h3>',
    '<p>This Agreement is governed by the laws of the state where the Firm maintains its principal office, with venue in that state and county where permitted.</p>',
    '<h3>22. Entire Agreement</h3>',
    '<p>This Agreement constitutes the entire understanding between the parties and may only be amended in writing.</p>',
    '<h3>23. Acceptance</h3>',
    '<p>By signing below, Client agrees to all terms contained herein. Electronic signatures are valid and enforceable.</p>',
  ]
}
